name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Tests
        run: echo "This job tests something"

      - name: Test 2
        run: echo "Rodando o segundo teste"