name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
          
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar Build
        run: echo "Olá, ${{ github.actor }}!"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar Dependências
        run: | 
          pip install flask
          pip install coverage


      - name: Tests
        run: | 
          python -m coverage run -m unittest -v tests/appTest.py
          python -m coverage report
